### ISSUE TITLE
Technisat schakelaar

### ISSUE THREAD

**Issue by Rahman227** [KyleTaylorParkins/com.technisat.smarthome#3]
Goedemorgen,

Ik had een vraagje over de technisat dubbelen schakelaar. Had een probleem met de 2de uitgang, die krijg ik niet geschakeld via de app wel via de module zelf.
Ik weet niet of dat met een update te regelen is? Trouwens ook de instructie voor het include proces moet T1 3 keer in 10 sec indrukken zijn, nu staat het exclude proces er.
Hoop dat het uitgang 2 probleem optelossen is :) mocht dat niet het geval zijn of je meer info nodig hebt hoor ik dat graag!

Met vriendelijke groet,
Rahman Yildirim

**Comment by KyleTaylorParkins** [comment]
Hi Rahman,

Bedankt voor het melden van je bevindingen!
De specificaties van Technisat in de handleiding welke ik eind november gedownload heb wijken helaas af van het apparaat. Daarna heeft Technisat alle documentatie van de website gehaald dus een nieuwere versie van de handleiding heb ik ook niet kunnen vinden. Gezien ik het apparaat zelf ook niet heb is dat lastig programmeren zo.
Na wat proberen heb ik de tweede uitgang wel werkend gekregen. Die versie van de app met deze wijzigingen is helaas ook nog niet perfect, daarom staat die nog steeds in de test fase. Je kunt hem hier vinden: https://homey.app/nl-nl/app/com.technisat.smarthome/Technisat-SmartHome/test/

Hopelijk werkt het daar wat beter mee. Ik hoop in de toekomst de ondersteuning goed af te maken dus houd de repo/app store in de gaten :)

Groet,

Kyle

**Comment by Rahman227** [comment]
Hi Kyle,

Super bedankt voor je reactie! Zal de test app downloaden en het even proberen.
Erg bedankt voor je antwoord :)
