### ISSUE TITLE
Technisat Switches with Homey & Google Home

### ISSUE THREAD

**Issue by JarekJ1986** [KyleTaylorParkins/com.technisat.smarthome#6]
I am satisfied with the app itself, but unfortunately the switches are not passed on to Google Home, so voice control is not possible. Can this be adjusted? Alexa doesn't see the switches either

**Comment by KyleTaylorParkins** [comment]
Hi Jarek,

The devices are setup correctly by the app. Homey maps the items to Google Home so there is nothing I can change in the app.
Try to re-connect Google Home to Homey. If the problem persist please contact the Homey support team.
